lua/mason/packages/codelldb/init.lua

fix(codelldb): update description and homepage

---

lua/mason-core/platform.lua
lua/mason-registry/node-debug2-adapter/init.lua

fix(node-debug2-adapter): fix build on Node >= 18

---

doc/mason.txt
lua/mason-core/package/init.lua
lua/mason/api/command.lua

Also make sure to exit neovim with an error exit code should one or more
installations fail.

feat(api): run :MasonInstall in blocking fashion if no UIs are attached

---

lua/mason-registry/cspell/init.lua
lua/mason-registry/index.lua

Its a spell checker for code variables and comments.
Didnt know what category to put it in so feel free to edit it as you see fit. Also afaik it supports most of the most popular languages so i didnt add anything in languages to reduce the clutter.

feat: add cspell spell checker

---

doc/mason.txt
doc/reference.md
lua/mason-registry/init.lua

Pretty low effort so far, but better than nothing.

docs: add doc/reference.md for more advanced use cases

---

lua/mason-core/functional/init.lua
lua/mason/api/command.lua

Reduces the modules required by mason when calling .setup() by 7, to a
total of 8.

feat: minimize modules required by .setup(), lazily require functional modules

---

lua/mason-core/managers/luarocks/init.lua
lua/mason-registry/index.lua
lua/mason-registry/luaformatter/init.lua
lua/mason/mappings/language.lua
tests/mason-core/managers/luarocks_spec.lua

Co-authored-by: Ali Shahid <canttell@gmail>

feat: add luaformatter

---

lua/mason-registry/fixjson/init.lua
lua/mason-registry/index.lua
lua/mason/mappings/language.lua

Add package for [fixjson](https://www.npmjs.com/package/fixjson)

feat: add fixjson

---

lua/mason-registry/index.lua
lua/mason-registry/rubocop/init.lua
lua/mason/mappings/language.lua

Support rubocop

---

lua/mason/ui/components/main/package_list.lua
lua/mason/ui/instance.lua

The idea is to subtly indicate which packages have been uninstalled or
installed during the current session.

feat(ui): highlight packages that have transitioned during the session

---

lua/mason-registry/cuelsp/init.lua
lua/mason-registry/index.lua
lua/mason/mappings/language.lua

Signed-off-by: Marcos Lilljedahl <marcosnils@gmail.com>

feat: add dagger's cuelsp support

---

lua/mason-registry/index.lua
lua/mason-registry/tectonic/init.lua
lua/mason/mappings/language.lua

This PR solved issue #248 . However I don't use tectonic, so I'm not sure what category it is. :thinking:

feat: add tectonic

---

README.md
doc/mason.txt
lua/mason/settings.lua
lua/mason/ui/instance.lua

This is enabled by default and can be disabled in settings.

feat(ui): check for new package versions when opening :Mason

---

lua/mason-core/ui/display.lua

fix(ui): use custom diagnostic config

---

lua/mason-core/installer/context.lua
tests/mason-core/installer/context_spec.lua

fix(installer): use /usr/bin/env bash shebang

---

lua/mason-registry/index.lua
lua/mason-registry/yamlfmt/init.lua
lua/mason/mappings/language.lua

A YAML formatter provided by Google.
https://github.com/google/yamlfmt

Add google/yamlfmt

---

lua/mason-registry/index.lua
lua/mason-registry/standardrb/init.lua
lua/mason/mappings/language.lua

Add standardrb linter/formatter for Ruby

---

lua/mason-registry/fantomas/init.lua
lua/mason-registry/index.lua
lua/mason/mappings/language.lua

This adds Fantomas, a formatter for the F# language.
@williamboman How to update generated files properly? I tried with make but got a lot of unrelated changes.

Add fantomas F# formatter

---

lua/mason-registry/buf-language-server/init.lua
lua/mason-registry/index.lua
lua/mason/mappings/language.lua

https://github.com/williamboman/mason.nvim/issues/362

feat: buf-language-server (#362)

---

lua/mason-core/managers/github/client.lua

feat(gh): set CLICOLOR_FORCE=0

---

lua/mason-core/functional/init.lua
lua/mason-core/functional/table.lua
lua/mason-core/platform.lua
tests/mason-core/functional/table_spec.lua
tests/mason-core/platform_spec.lua

- tests(platform): add tests for os_distribution
- refactor(platform): more functional approach to parsing

refactor(platform): more functional approach to parsing

---

lua/mason-registry/shfmt/init.lua
lua/mason-registry/yamlfmt/init.lua

fix(shfmt, yamlfmt): fix windows detection

---

lua/mason-core/managers/std/init.lua
lua/mason/health/init.lua

feat(std): attempt gzip on windows

---

lua/mason-core/managers/cargo/init.lua
lua/mason-core/managers/github/client.lua
lua/mason-core/optional.lua
lua/mason-core/result.lua
lua/mason-registry/flux-lsp/init.lua
lua/mason-registry/move-analyzer/init.lua
lua/mason-registry/wgsl-analyzer/init.lua
tests/mason-core/managers/cargo_spec.lua
tests/mason-core/managers/github_client_spec.lua
tests/mason-core/optional_spec.lua
tests/mason-core/result_spec.lua

This is all pretty overkill, especially considering the small amount of
packages based on git-based crates.

feat(cargo): improve handling of git-based crates

---

README.md
doc/mason.txt
lua/mason/init.lua
lua/mason/settings.lua
tests/mason/setup_spec.lua

feat: add setting to control PATH modification

---

lua/mason-core/log.lua

fix(log): use "log" stdpath

---

lua/mason-registry/gradle-language-server/init.lua
lua/mason-registry/index.lua
lua/mason/mappings/language.lua

feat: add gradle-language-server

---

lua/mason-registry/visualforce-language-server/init.lua

This is no longer needed as their releases now contain complete assets.

fix(visualforce-language-server): remove custom release resolution code

---

lua/mason-registry/astro-language-server/init.lua

Also see https://github.com/williamboman/mason-lspconfig.nvim/pull/75

feat(astro): vendor typescript

---

lua/mason-registry/verible/init.lua

feat(verible): add linux_x64_gnu

---

lua/mason-registry/index.lua
lua/mason-registry/pint/init.lua
lua/mason/mappings/language.lua

Add support for Laravel's official formatting tool: Laravel Pint.
Closes #611
CC @nunomaduro

Add Laravel Pint

---

lua/mason-core/platform.lua

fix(platform): also accept exit code 1 when checking ldd version

---

lua/mason-registry/rustfmt/init.lua

relate with issue in comment https://github.com/williamboman/mason.nvim/pull/642#issuecomment-1305153493

fix(rustfmt): can not install

---

lua/mason-registry/apex-language-server/init.lua

fix(apex-language-server): update jar file path

---

lua/mason-registry/visualforce-language-server/init.lua

fix(visualforce-language-server): update script path

---

lua/mason-registry/verible/init.lua

fix(verible): properly format asset file

---

lua/mason-registry/index.lua
lua/mason-registry/ruff/init.lua
lua/mason/mappings/language.lua

feat(registry): add ruff

---

README.md
doc/mason.txt
lua/mason-core/managers/pip3/init.lua
lua/mason/settings.lua
tests/mason-core/managers/pip3_spec.lua

feat(pip): add setting to upgrade pip before installing packages

---

lua/mason-registry/dhall-lsp/init.lua

fix(dhall-lsp): github release doesn't always include lsp server asset

---

lua/mason-registry/yapf/init.lua

fix(yapf): install toml to support parsing .toml config files

---

README.md
doc/mason.txt
lua/mason-core/managers/powershell/init.lua
lua/mason/health/init.lua

`powershell.exe` is apparently legacy software now.

chore: use pwsh instead of powershell

---

lua/mason-core/managers/npm/init.lua
lua/mason/ui/components/main/package_list.lua
lua/mason/ui/instance.lua

Also improve how logs are displayed.

feat(ui): hoist "Installing" and "Failed" package groups to the top

---

doc/mason.txt

Probably helpful for some people.

docs: add more helpfile tips

---

lua/mason-core/package/init.lua
lua/mason/init.lua
lua/mason/terminator.lua
tests/mason/terminator_spec.lua
tests/minimal_init.vim

Also explicitly terminate all active handles on VimLeavePre.

feat: show warning message when exiting neovim with active installations

---

lua/mason/init.lua
lua/mason/terminator.lua
tests/mason/terminator_spec.lua

Give a very generous grace period for processes to terminate gracefully
before forcefully killing them, to ensure none linger.

feat(terminator): send SIGKILL after some delay after SIGTERM

---

tests/mason-core/functional/function_spec.lua
tests/mason-core/functional/list_spec.lua
tests/mason-core/functional/relation_spec.lua
tests/mason-core/functional/table_spec.lua

Forgot to include these in the last commit.

test(functional): add some tests

---

lua/mason-registry/fourmolu/init.lua
lua/mason-registry/index.lua
lua/mason/mappings/language.lua

Add [fourmolu](https://github.com/fourmolu/fourmolu/) installer. It's an Haskell code formatter and currently is released only for linux x86_64 and macos x86_64.
Thanks in advance

Add fourmolu formatter

---

README.md
doc/mason.txt
lua/mason-core/managers/powershell/init.lua
lua/mason/health/init.lua

This reverts commit e64dffb84e84e67836a05707a95b1d81fe698481.
Closes #764.

Revert "chore: use pwsh instead of powershell (#706)"

---

lua/mason-registry/index.lua
lua/mason-registry/nil/init.lua
lua/mason/mappings/language.lua

Add the NIx Language Server (https://github.com/oxalica/nil) to the registry

feat(registry): add nil

---

lua/mason-core/spawn.lua
tests/mason-core/spawn_spec.lua

fix(spawn): always expand cmd if PATH is not modified

---

lua/mason-core/spawn.lua
tests/mason-core/spawn_spec.lua

This reverts commit dd04b4105e84620685c37efb6ca935d282e11465.

Revert "fix(spawn): always expand cmd if PATH is not modified (#773)"

---

lua/mason-core/installer/context.lua
lua/mason-registry/index.lua
lua/mason-registry/smithy-language-server/init.lua
lua/mason/mappings/language.lua

Add support for the [smithy-language-server](https://github.com/awslabs/smithy-language-server) for the [Smithy IDL](https://smithy.io/2.0/index.html)
This addresses issue #794

feat(registry): add smithy-language-server

---

lua/mason/ui/colors.lua

Related PR:
- https://github.com/williamboman/mason.nvim/pull/636

fix(ui): do not override existing MasonNormal hl group

---

lua/mason-registry/vala-language-server/init.lua

The release assets are just a .tar.xz archive of the git repo itself.
Closes #845.

fix(vala-language-server): use git tag source instead of releases

---

lua/mason-registry/openscad-lsp/init.lua

fix(openscad-lsp): fix bin definition

---

README.md
doc/mason.txt

fix typo from https://github.com/williamboman/mason.nvim/pull/906

docs: fix default value for `ui.height`

---

lua/mason-registry/blackd-client/init.lua
lua/mason-registry/index.lua
lua/mason/mappings/language.lua

FYI, there are no Windows builds available.

feat: add blackd-client for Python

---

lua/mason-registry/zls/init.lua

fix(zls): fix Windows x64 target

---

lua/mason-registry/index.lua
lua/mason-registry/veryl-ls/init.lua
lua/mason/mappings/language.lua

I want to add veryl language server.

feat(registry): add veryl language server

---

lua/mason-registry/index.lua
lua/mason-registry/latexindent/init.lua
lua/mason/mappings/language.lua

Adding [latexindent](https://github.com/cmhughes/latexindent.pl) formatter.
Closes #261

feat(registry): add latexindent formatter

---

README.md

works both ways and its cleaner to not have the brackets

removed bracket from packer install code

---

lua/mason-registry/docker-compose-language-service/init.lua
lua/mason-registry/dockerfile-language-server/init.lua
lua/mason-registry/hadolint/init.lua
lua/mason-registry/index.lua
lua/mason/mappings/language.lua

Installs [docker-compose-language-service](https://github.com/microsoft/compose-language-service)

feat: add docker-compose-language-service

---

lua/mason-registry/ansible-lint/init.lua
lua/mason-registry/index.lua
lua/mason/mappings/language.lua

Adds [ansible-lint](https://github.com/ansible/ansible-lint) to the registry.  
Resolves #930

feat(registry): add ansible-lint

---

lua/mason-registry/vacuum/init.lua

The npm package is just a Node.js script that downloads these.

refactor(vacuum): use github source

---

lua/mason-registry/terraform-ls/init.lua

fix(terraform-ls): use releases.hashicorp.com

---

lua/mason-core/installer/context.lua
lua/mason-core/installer/init.lua
lua/mason-core/installer/linker.lua
lua/mason-core/package/init.lua
lua/mason-core/path.lua
lua/mason-core/receipt.lua
lua/mason-core/result.lua
tests/mason-core/installer/installer_spec.lua
tests/mason-core/installer/linker_spec.lua

- refactor(linker): dedup and simplify
- refactor(receipt): add :write() method

refactor: simplify linker & receipt writing

---

lua/mason-core/fs.lua
lua/mason-core/installer/context.lua
tests/helpers/lua/test_helpers.lua
tests/mason-core/installer/context_spec.lua
tests/mason-core/installer/installer_spec.lua

Also add some more ctx.fs methods.

feat(InstallContext): add strict_mode flag

---

lua/mason-core/semver.lua
lua/mason-vendor/semver.lua
selene.toml

This will be used to compare semver versions, for example:
```lua
local v1 = try(semver.parse("1.0.0"))
local v2 = try(semver.parse("v2.0.0"))
local _ = v1 < v2 -- true
```

feat: add semver module

---

lua/mason-core/package/init.lua

The mason-core.package module is loaded whenever there's anything interfacing with Mason packages (i.e. pretty often).
Some of the modules imported at the top-level is used pretty infrequently, so we lazily require these instead.

refactor(package): lazy-require modules

---

lua/mason-registry/index/cmake-lint/init.lua
lua/mason-registry/index/init.lua
lua/mason/mappings/language.lua

feat(registry): add cmake-lint

---

lua/mason-core/installer/context.lua
tests/helpers/lua/test_helpers.lua

fix: fix writing pyvenv module wrapper

---

PACKAGES.md
lua/mason-registry/index/php-cs-fixer/init.lua

Also submitted a [PR#1437](https://github.com/jose-elias-alvarez/null-ls.nvim/pull/1437) in the null-ls.nvim project

php-cs-fixer: use new PHP-CS-Fixer/PHP-CS-Fixer repo

---

lua/mason-registry/index/js-debug-adapter/init.lua

fix(js-debug-adapter): fix build script

---

lua/mason-registry/index/golangci-lint/init.lua

feat(golangci-lint): support linux_arm64

---

.github/workflows/tests.yml
doc/mason.txt

fix(doc): duplicate helptag

---

lua/mason-registry/sources/github.lua
lua/mason/ui/colors.lua
lua/mason/ui/components/header.lua
lua/mason/ui/components/help/init.lua
lua/mason/ui/instance.lua
lua/mason/ui/palette.lua

feat(ui): display warning and error message if registry is not installed

---

lua/mason-core/package/init.lua
lua/mason-registry/init.lua
lua/mason/ui/components/main/package_list.lua

This is an attempt at resolving this issue https://github.com/williamboman/mason-lspconfig.nvim/issues/116. Let me know if there's a better/preferred way to do this!

feat(registry): add ability to register package aliases

---

lua/mason-registry/sources/github.lua

Accessing binary data from the stdout of pwsh.exe's iwr seems to be causing data corruption leading to inability to unpack the archive.
Closes #1187.

fix(windows): download registry archive to file instead of piping data

---

lua/mason-core/installer/managers/std.lua

fix(std): manually call zstd on Windows

---

lua/mason/health.lua

fix(health): add scheduler in python3_host_prog check

---

lua/mason-core/installer/linker.lua
tests/mason-core/installer/linker_spec.lua

1) FAT (FAT32, exFAT, etc.) file systems doesn't support symlinks.
2) You need administrator access in order to create symlinks.
This was working for me locally because I'm running a NTFS fs with
"Developer Mode" enabled in Windows 10, which bypasses administrator
requirement for mklink.
Instead we uv_fs_rename() links. This should effectively be the same,
but will require special handling down the road if/when for example
multiple package versions can be installed at the same time. When
unlinking a package the renamed files should me moved back into the
package installation directory, instead of simply being unlinked (i.e.
removed).
Closes #1251.

fix(linker): don't symlink on Windows

---

lua/mason-core/installer/registry/providers/pypi.lua
tests/mason-core/installer/registry/providers/pypi_spec.lua

fix(pypi): also provide install_extra_args to pypi.install

---

lua/mason/settings.lua
lua/mason/ui/components/main/package_list.lua

feat(ui): add keymap setting for toggling package installation log

---

lua/mason-core/installer/init.lua
lua/mason-core/path.lua
tests/mason-core/installer/installer_spec.lua
tests/mason-core/managers/cargo_spec.lua
tests/mason-core/managers/composer_spec.lua
tests/mason-core/managers/dotnet_spec.lua
tests/mason-core/managers/gem_spec.lua
tests/mason-core/managers/git_spec.lua
tests/mason-core/managers/github_spec.lua
tests/mason-core/managers/go_spec.lua
tests/mason-core/managers/luarocks_spec.lua
tests/mason-core/managers/npm_spec.lua
tests/mason-core/managers/opam_spec.lua
tests/mason-core/managers/pip3_spec.lua
tests/mason-core/terminator_spec.lua
tests/minimal_init.vim

- refactor: change package build directory
- feat(installer): lock package installation

feat(installer): lock package installation

---

lua/mason-core/installer/registry/init.lua
lua/mason-core/installer/registry/providers/cargo.lua
lua/mason-core/installer/registry/providers/composer.lua
lua/mason-core/installer/registry/providers/gem.lua
lua/mason-core/installer/registry/providers/generic/init.lua
lua/mason-core/installer/registry/providers/github/init.lua
lua/mason-core/installer/registry/providers/github/release.lua
lua/mason-core/installer/registry/providers/golang.lua
lua/mason-core/installer/registry/providers/luarocks.lua
lua/mason-core/installer/registry/providers/npm.lua
lua/mason-core/installer/registry/providers/nuget.lua
lua/mason-core/installer/registry/providers/opam.lua
lua/mason-core/installer/registry/providers/pypi.lua
lua/mason/api/command.lua
tests/mason/setup_spec.lua

Now also supports completing versions if completion is triggered when specifying
a version, e.g. "rust-analyzer@".
https://github.com/williamboman/mason.nvim/assets/6705160/b3c2e5dd-ffd2-4181-bdf4-3ae337e2ba27

feat(command): improve completion for :MasonInstall

---

lua/mason-core/installer/managers/cargo.lua
lua/mason-core/installer/managers/composer.lua
lua/mason-core/installer/managers/gem.lua
lua/mason-core/installer/managers/golang.lua
lua/mason-core/installer/managers/luarocks.lua
lua/mason-core/installer/managers/npm.lua
lua/mason-core/installer/managers/nuget.lua
lua/mason-core/installer/managers/opam.lua
lua/mason-core/installer/managers/pypi.lua
lua/mason-core/installer/managers/std.lua
lua/mason-core/installer/registry/schemas.lua
lua/mason-core/managers/std/init.lua
tests/mason-core/installer/managers/cargo_spec.lua
tests/mason-core/installer/managers/composer_spec.lua
tests/mason-core/installer/managers/gem_spec.lua
tests/mason-core/installer/managers/golang_spec.lua
tests/mason-core/installer/managers/luarocks_spec.lua
tests/mason-core/installer/managers/npm_spec.lua
tests/mason-core/installer/managers/nuget_spec.lua
tests/mason-core/installer/managers/opam_spec.lua
tests/mason-core/installer/managers/pypi_spec.lua

This should give better insights into the installation progress.

feat(installer): write more installation output to stdout

---

lua/mason-core/package/init.lua
lua/mason/ui/components/main/package_list.lua

feat(ui): display package deprecation message

---

lua/mason/ui/components/main/package_list.lua

Less intrusive display of deprecated packages that aren't installed. Diagnostics
should only be for things that require
the user's attention.

feat(ui): don't use diagnostic messages for displaying deprecated, uninstalled, packages

---

lua/mason-core/installer/registry/init.lua
tests/mason-core/installer/registry/installer_spec.lua
tests/mason-core/installer/registry/providers/github/release_spec.lua

fix(installer): retain unmapped source fields

---

lua/mason/settings.lua
lua/mason/ui/components/header.lua
lua/mason/ui/components/help/init.lua
lua/mason/ui/instance.lua

feat(ui): add setting to toggle help view

---

lua/mason-core/installer/linker.lua
lua/mason-core/path.lua
tests/mason-core/installer/linker_spec.lua
tests/mason-core/path_spec.lua

feat(linker): use relative targets for symlinks

---

lua/mason-registry/sources/file.lua

Instead of spawning a separate yq process for each registry package, utilize multi-document parsing through a single
process.
This should have significant performance improvements on all platforms, but especially Windows, due to bottlenecks
caused by AV software.
IMPORTANT: Writing all package definitions as-is via stdin like this works because packages in the registry (at least
the core registry) must start with a document header (---), effectively acting as a document separator.

perf(registry): significantly improve the "file:" protocol performance

---

lua/mason/ui/components/json-schema.lua

fix(ui): fix rendering JSON schemas

---

lua/mason-core/ui/display.lua

Hi! 👋
This pull request would only change (minimally) the way which the plugin calculates it's window size.
Fixes #1678

fix(ui): reposition window if border is different than "none"

---

lua/mason-registry/init.lua
lua/mason-registry/sources/file.lua
lua/mason-registry/sources/github.lua
lua/mason-registry/sources/init.lua
lua/mason-registry/sources/lua.lua
tests/mason-registry/sources/collection_spec.lua

This is to better handle misconfigurations by users.

fix(registry): ensure there's no duplicate registry entries

---

lua/mason-core/installer/managers/pypi.lua
tests/mason-core/installer/managers/pypi_spec.lua

fix(pypi): pass --no-user flag
