mason-org/mason.nvim

lua/mason-registry/eslint_d/init.lua, lua/mason-registry/index.lua
This PR adds support for the eslint_d linter
its the recommended linter by null-ls for js/ts files because it creates a eslint server in the background to make linting much faster compared to just using the default eslint command for every save. (speeds up linting by 400+%)
=> feat: add eslint_d linter

lua/mason/ui/components/main/package_list.lua
The sticky cursor is a bit too jittery now when a package transitions between the different visual groupings - now it'll only remain sticky as long as it stays within the current group after a state update
=> feat(ui): segmentize sticky cursor for better UX

lua/mason-core/async/init.lua
This number is completely arbitrary - the previous value was chosen at
random. Increasing it now to support long-running, blocking,
installations.
=> fix(async): increase vim.wait time

lua/mason-core/ui/display.lua, lua/mason/api/command.lua, lua/mason/ui/components/main/package_list.lua, lua/mason/ui/init.lua, lua/mason/ui/instance.lua
This ensures users see the progress output immediately, instead of
having to scroll down to see it.
=> feat(ui): bring focus to the installation section when :MasonInstall

lua/mason-registry/vint/init.lua
If you use the package name `vint` it appears to work but https://github.com/Vimjas/vint/issues/247 happens. Instead, use the package name `vim-vint`.
=> fix: correct package name for vint is vim-vint

lua/mason/ui/instance.lua
To allow styling it differently.
Example from neovim core: https://github.com/neovim/neovim/blob/7961f79904f6583ed3279fb1c73f2107ce9603ef/runtime/lua/vim/lsp/buf.lua#L807-L809
=> feat(ui): pass kind=mason-lang to vim.ui.select

lua/mason-core/ui/display.lua, lua/mason/ui/instance.lua
The terminate handler should only really be called when the handle is
terminated. By calling it immediately (to initialize UI state), any
queued packages would be reset to either the "installed" or
"uninstalled" group, when they really should remain "queued".
=> fix(ui): don't call terminate handler when setting up handle

lua/mason-registry/taplo/init.lua
I don't like this kind of mixing of installation sources, but I figured
this could be a good first experiment.
=> feat(taplo): use prebuilt binary if available

lua/mason/ui/palette.lua
This avoids overriding user-provided highlight group definitions.
Discussed in #133.
https://neovim.io/doc/user/syntax.html#:hi-default
=> Add default option to highlights

lua/mason-registry/selene/init.lua
The filename should be `selene-%s-windows.zip` instead of `selene-%s-win64.zip`.
=> fix(selene): download error in Windows

lua/mason-registry/taplo/init.lua
=> fix(taplo): write receipt when installing via cargo

lua/mason-core/installer/context.lua, lua/mason-registry/debugpy/init.lua
In the example https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#python, we load module `debugpy.adapter` not `debugpy`
=> debugpy load module `debugpy.adapter` instead of `debugpy`

doc/mason.txt
In this case, using `packages` instead of `languages` makes more sense.
In the example given, we're not installing just "languages" but also
other packages (a formatter)
=> docs: change to a more appropriate word

lua/mason-registry/omnisharp-mono/init.lua
This `run` script can only be executed from its installation location
(i.e. symlink = bad).
=> fix(omnisharp-mono): don't link directly to the `run` script

lua/mason-core/installer/context.lua, tests/mason-core/installer/context_spec.lua, tests/mason-core/installer/linker_spec.lua
- feat(installer): don't write exec wrappers for targets that don't exist
- test(installer): add spec files for context and linker
=> test(installer): add spec files for context and linker

lua/mason/ui/components/header.lua, lua/mason/ui/instance.lua
The `?` keymap has annoyed me personally for a long time. I don't like
overriding backwards search, it's far more useful than toggling the help
view.
=> fix(ui): use `g?` to toggle help instead of `?`

lua/mason/ui/components/help/init.lua
Help menu mapping did not change in https://github.com/williamboman/mason.nvim/pull/326
=> fixes help menu mapping mismatch

lua/mason-registry/fantomas/init.lua
Bugfix for the fantomas binary name.
Tested with `:MasonInstall fantomas@5.0.0-beta-009`
=> Bugfix for the fantomas binany name

lua/mason-registry/codelldb/init.lua
The codelldb executable has a relative dynamic link.
Fixes #371.
=> fix(codelldb): don't symlink executable directly

lua/mason-registry/clojure-lsp/init.lua
This allows clojure-lsp installed with mason to work on musl based distros like Alpine.
For reference, the clojure-lsp commit that introduced musl to static builds: https://github.com/clojure-lsp/clojure-lsp/commit/a76653e221b568336c0b99fcc3763c0c2b7ef4ec
=> fix(clojure-lsp): use the static release of clojure-lsp when running on musl libc

lua/mason-core/managers/github/init.lua, lua/mason-registry/spectral-language-server/init.lua
The npm package is an unofficial one, and it seems to be relying on a
build script (broken) to execute during installation, instead of pre-packaging
it.
Fixes #463.
=> fix(spectral-language-server): build directly from source

lua/mason-registry/yamlfmt/init.lua
no longer requires 'go' to build
=> feat(yamlfmt): use the pre-built binary package

lua/mason-registry/stylua/init.lua
This is because I'm using Neovim in Ubuntu that runs on Docker which runs on Apple M1 MacBook.
=> fix(stylua): cannot be installed on arm64 Linux

lua/mason-registry/index.lua, lua/mason-registry/java-debug-adapter/init.lua, lua/mason-registry/java-test/init.lua, lua/mason/mappings/language.lua
closes https://github.com/williamboman/mason.nvim/issues/433
I've opted for using the prebuilt files extracted from .vsix because maven takes a while to build.
Not sure if we should link `java-test` or not, since it's more like a 'lib' than an executable (should it still be in the DAP category?).
usage with [nvim-jdtls#java-debug](https://github.com/mfussenegger/nvim-jdtls#java-debug-installation) / [nvim-jdtls#vscode-java-test](https://github.com/mfussenegger/nvim-jdtls#vscode-java-test-installation):
```lua
local function get_install_path(package_name)
return require("mason-registry").get_package(package_name):get_install_path()
end
local bundles = {
vim.fn.glob(
-- or
-- get_install_path("java-debug-adapter") .. "extension/server/com.microsoft.java.debug.plugin-*",
vim.fn.stdpath …
```
=> feat: java-debug-adapter, java-test

lua/mason-registry/elixir-ls/init.lua
This commit makes elixir-ls installer link not just a language server binary, but also a debugger one.
Additionally, it explicitly states the names of the binaries exposed, since nvim-lspconfig does not set elixir-ls command by default.
=> Make elixir-ls installer expose debugger binary

lua/mason-registry/erg-language-server/init.lua, lua/mason-registry/index.lua, lua/mason/mappings/language.lua
Hi, first of all, thanks for your amazing work!
Recently, I have added the [erg-language-server](https://github.com/erg-lang/erg-language-server) to `nvim-lspconfig` : PR -> https://github.com/neovim/nvim-lspconfig/pull/2165
It would be really nice if I can add this to `mason.nvim`.
A generic statically typed language that can deeply improve the Python ecosystem.
=> feat: add erg-language-server

lua/mason-registry/dhall-lsp/init.lua
fixes the following error
```console
...acker/start/mason.nvim/lua/mason-core/installer/init.lua:113: ...r/start/mason.nvim/lua/mason-registry/dhall-lsp/init.lua:58: Unable to find the dhall-lsp-server release asset in the GitHub release.
```
see
- https://github.com/dhall-lang/dhall-haskell/releases/tag/1.41.2
- https://github.com/dhall-lang/dhall-haskell/releases/tag/1.41.1
=> fix(dhall): new assets have capitalized naming

lua/mason-registry/iferr/init.lua, lua/mason-registry/index.lua, lua/mason/mappings/language.lua
Hi! I've recently been configuring this other package https://github.com/olexsmir/gopher.nvim and most of the supported tools are included in mason already, so I wondered if `iferr` would also be a good addition.
Thanks a lot in advance and thanks for writing this plugin! it makes my life so much easier.
=> feat(registry): add iferr tool for Go

lua/mason-registry/codelldb/init.lua
These binaries are linked to glibc.
=> fix(codelldb): require GNU compatible system on linux

lua/mason-registry/dprint/init.lua, lua/mason-registry/index.lua
closes #558 
- uses npm not cargo for installation
- the npm package of dprint provides a pre-compiled binary
- no languages specified, as it depends on selected plugins in per-project config file and dprint itself does not provide any language support by default
=> feat(registry): add dprint formatter

lua/mason-registry/goimports-reviser/init.lua
=> fix(goimports-reviser): use prebuilt github assets

lua/mason-registry/index.lua, lua/mason-registry/nxls/init.lua, lua/mason/mappings/language.lua
=> feat(registry): add nxls

lua/mason-registry/taplo/init.lua
Fixes #612
Does not address architectures. Tested on linux/x86_64.
=> fix(taplo): rename files to match upstream

lua/mason/providers/client/init.lua
=> Fix error when using client-side github provider

lua/mason-core/managers/gem/init.lua, tests/mason-core/managers/gem_spec.lua
Closes #570.
Closes williamboman/mason-lspconfig.nvim#94.
=> fix(gem): don't format executable

lua/mason-core/ui/display.lua, lua/mason/init.lua, lua/mason/ui/colors.lua, lua/mason/ui/init.lua, lua/mason/ui/instance.lua, lua/mason/ui/palette.lua, tests/mason-core/ui_spec.lua
This allows for further customization of Mason's popup window (more
specifically its background color). Note that this is already possible
by changing the `NormalFloat` highlight, but it impacts floating windows
globally. We leverage 'winhighlight' to introduce a specific
`MasonNormal` highlight group to allow targeting Mason only.
Closes #635.
=> feat(ui): add MasonNormal highlight

lua/mason-registry/rome/init.lua
Rome has been defaulting to quite an old version. They just released a new major 10.0.0, so I'd suggest dropping the old default and instead just going with the newest from npm.
=> fix(rome): drop default version pin

lua/mason-registry/colorgen-nvim/init.lua, lua/mason-registry/index.lua
Feel free to close if this is out of scope for `mason.nvim`.
I'd like to experiment with using `colorgen-nvim` to generate a colorscheme on-the-fly with a Neovim command in my configuration.
This PR adds `colorgen-nvim` as an installable package.
=> feat(registry): add colorgen-nvim

lua/mason-registry/tectonic/init.lua
This is far from ideal. This is needed because the repository hosts
multiple different projects. The current mechanism to resolve the
"latest" release is not compatible with this and may end up selecting a
release for a different project.
Closes #544.
=> fix(tectonic): pin version

lua/mason/ui/components/main/package_list.lua
I think this has better affordance and better indicates that the log is
truncated to a single line and can actually be expanded.
=> feat(ui): change log line number formatting in tail output

lua/mason-registry/mockdebug/init.lua
Add a missing bin link for the mock debug adapter after building it up.
=> Add a binary link for the mock debug adapter.

lua/mason-core/ui/display.lua
Simply setting it to true won't override sub-items such as a user's severity config. Some users may for example have set the `virtual_text` severity to only show ERRORs, causing Mason's INFO diagnostics to not be displayed.
=> fix(ui): set severity min & max for namespaced diagnostic config

lua/mason-core/installer/registry/expr.lua, lua/mason-core/result.lua, tests/mason-core/installer/registry/expr_spec.lua, tests/mason-core/result_spec.lua
This is (soon) to be used when installing package definitions from
https://github.com/mason-org/mason-registry/. See for example:
https://github.com/mason-org/mason-registry/blob/7df69dd2a73efc3a08520552ca64597d1db5f4fb/packages/go-debug-adapter/package.yaml#L16
=> feat: add expr module

PACKAGES.md, lua/mason-registry/ruff-lsp/init.lua
Change `ruff-lsp` package  category to 'LSP'.
=> fix(registry): change ruff-lsp category from linter to lsp

lua/mason-core/managers/powershell/init.lua, tests/mason-core/managers/powershell_spec.lua
Also write to stdin pipe asynchronously.
=> feat(powershell): set $ErrorActionPreference = "Stop";

lua/mason/api/command.lua
This fixes situations where the UI would be come desynced should a
package installation complete immediately (i.e. in the very same event
loop as it was started in).
=> fix(api/command): instantiate UI before package installation

lua/mason-registry/cueimports/init.lua, lua/mason-registry/index.lua, lua/mason/mappings/language.lua
`cueimports` is a newish tool for automatically managing imports for the CUE language.
=> feat(registry): add cueimports

lua/mason-core/managers/powershell/init.lua, tests/mason-core/managers/powershell_spec.lua
Powershell doesn't seem to be closing the process after commands finsh
executing and stdin is closed, not entirely sure why. This seems to fix
the issue.
=> fix(powershell): terminate stdin with newline

lua/mason-core/managers/dotnet/init.lua, tests/mason-core/managers/dotnet_spec.lua
I contract for a number of organizations and I'm never authenticated to all the private nuget feeds at once so installing tools always fails without this flag. I believe this should be a safe addition.
[Docs](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-install)
`--ignore-failed-sources`
Treat package source failures as warnings.
=> feat(dotnet/init.lua): ignore failed sources

lua/mason-core/managers/github/client.lua, lua/mason-core/providers/init.lua, lua/mason-registry/vls/init.lua, lua/mason/providers/client/gh.lua, lua/mason/providers/registry-api/init.lua
This is no longer supported by mason-registry-api.
=> refactor(providers): remove ?include_prerelease query param

lua/mason-registry/rust-analyzer/init.lua
Rust analyzer recently changed their packaging for windows to use zip
https://github.com/rust-lang/rust-analyzer/pull/13876
=> fix(windows): change rust analyzer to use the new .zip archives

lua/mason-registry/fourmolu/init.lua, lua/mason-registry/lua-language-server/init.lua
This won't be a problem once https://github.com/mason-org/mason-registry
is integrated because package installations won't independently execute
code.
Fixes #891.
=> fix: avoid calling API functions inside fast event

lua/mason-registry/crystalline/init.lua
CI failed at https://github.com/mason-org/mason-registry/pull/305
=> fix(crystalline): update linux asset name

lua/mason-registry/drools-lsp/init.lua, lua/mason-registry/index.lua, lua/mason/mappings/language.lua
This PR adds support for Red Hat's [Drools Rule Language](https://docs.drools.org/latest/drools-docs/docs-website/drools/language-reference/index.html#con-drl_drl-rules) (ft=`drools`, ext=`.drl`). The [drools-lsp](https://github.com/kiegroup/drools-lsp/) server config was recently merged into [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig) (also written by me). The generated doc link in nvim-lspconfig is [here](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#drools_lsp).
The companion PR in mason-lspconfig.nvim is [here](https://github.com/williamboman/mason-lspconfig.nvim/pull/125).
_Thank you so much!_
Signed-off-by: David Ward <dward@redhat.com>
=> feat(registry): add drools-lsp

lua/mason-registry/editorconfig-checker/init.lua
CI failed at https://github.com/mason-org/mason-registry/pull/310.
=> fix(editorconfig-checker): update Windows assets

lua/mason-core/ui/display.lua
This ensures that the window doesn't overlap the status bar.
=> feat(ui): nicer bottom offset

README.md, doc/mason.txt, lua/mason-core/ui/display.lua, lua/mason/settings.lua
Allow user to customize their window height and width.
Also tweaks the default height and width so it looks better when `cmdheight` is 0:
Before this commit:
After this commit:
=> feat(ui): customizable window height and width

lua/mason-registry/drools-lsp/init.lua
fix(drools-lsp): leverage simpler -jar syntax now that drools-lsp supports it
[This PR](https://github.com/kiegroup/drools-lsp/pull/7) in `kiegroup/drools-lsp` was merged and a new release was built, making this PR doable.
Signed-off-by: David Ward <dward@redhat.com>
=> fix(drools-lsp): leverage simpler -jar syntax now that drools-lsp supports it

lua/mason-registry/drools-lsp/init.lua
fix(drools-lsp): remove unused shell exec wrapper
Signed-off-by: David Ward <dward@redhat.com>
=> fix(drools-lsp): remove unused shell exec wrapper

lua/mason-core/managers/github/init.lua, lua/mason-core/managers/std/init.lua
For windows platform it will use zstd first as the windows tar implementation hangs.
Fixes #947.
=> feat(windows): manually decompress zstd archives before untar

lua/mason-core/managers/std/init.lua
This accidentally remained in #963.
=> refactor(std): remove zstd from untar

lua/mason/api/command.lua
Now supports passing options such as `:MasonInstall --force --debug`,
which will translate to the following install opt table:
```lua
{
"force" = true,
"debug" = true
}
```
=> feat(api/command): accept boolean option notation

lua/mason-registry/golangci-lint/init.lua
Thank you for your amazing work.
The team behind golangci-lint discourages installation using `go install` as stated in the official [documentation](https://golangci-lint.run/usage/install/#install-from-source).
This pull request changes the installation of golangci-lint to use the github manager instead of the go one.
=> feat(golangci-lint): change installation method

lua/mason-registry/lua-language-server/init.lua
Mostly just a little cleanup.
Nothing is currently broken with mason (as of right now at least)
- Stop downloading extra files which are meant for the server's VSCode extension
- Use the new organization URL :)
Tested on my Window11 machine with Neovim `0.8.3`
=> feat(lua-language-server): update source repo

lua/mason-registry/init.lua, lua/mason/init.lua, scripts/lua/mason-scripts/mason/generate.lua, scripts/lua/mason-scripts/mason/generate_package_index.lua
This further reduces the amount of modules loaded during setup.
=> refactor: load mason-registry.sources directly

lua/mason-registry/index/pydocstyle/init.lua
Pydocstyle only supports `pyproject.toml` if the `toml` package is installed.
=> feat(registry): ensure pyproject.toml support for pydocstyle

lua/mason/init.lua, tests/mason/setup_spec.lua
Enables leveraging env var to expand Mason paths, e.g. `vim.fn.expand("$MASON/share/jdtls/org.eclipse.equinox.launcher.jar")`.
=> feat: set $MASON and $MANPATH

lua/mason/init.lua, tests/mason/setup_spec.lua
After reading through `manpath(1)` a bit more thoroughly, this should not be needed due to `PATH` already being set.
=> refactor: don't set MANPATH explicitly

lua/mason-core/managers/powershell/init.lua, tests/mason-core/managers/powershell_spec.lua
Calling vim.fn.executable in the module scope has potential to error
if the module is required outside of the main loop.
=> refactor(powershell): remove .script and fix fast API error

lua/mason-core/package/init.lua
Also display a more helpful error message in the UI, as well as terminating the handle if it's not yet terminated.
=> fix(package): emit registry event on abnormal failures

lua/mason-registry/index/init.lua, lua/mason-registry/index/snakefmt/init.lua, lua/mason/mappings/language.lua
This adds [`snakefmt`](https://github.com/snakemake/snakefmt), a formatter for the workflow management system [`Snakemake`](https://github.com/snakemake/snakemake).
I copied this from the `black` init.lua, I'm not sure if the duplicated snakefmt in this line is needed:
```lua
pip3.packages { "snakefmt", bin = { "snakefmt" } },
```
=> feat(registry): add snakefmt

CONTRIBUTING.md, lua/mason/settings.lua
The current, and henceforth deprecated, Lua-based package registry bundled with `mason.nvim` is still the primary
registry. The [new registry](https://github.com/mason-org/mason-registry/) is being added now as a secondary registry to
ensure a smooth roll-out. Over time, the Lua-based packages in `mason.nvim` will gradually be removed and replaced by
packages provided by the new registry. This migration will be entirely seamless.
=> feat: add github:mason-org/mason-registry as the secondary default registry

README.md
Made the wording about where Mason packages are installed clearer.
=> docs: clarify installation location and add more help links

lua/mason-core/async/init.lua, lua/mason-core/functional/init.lua, lua/mason-core/installer/linker.lua, lua/mason-core/installer/managers/pypi.lua, lua/mason-core/installer/registry/init.lua, lua/mason-core/installer/registry/link.lua, lua/mason-core/installer/registry/providers/github.lua, lua/mason-core/managers/cargo/init.lua, lua/mason-core/managers/go/init.lua, lua/mason-core/managers/pip3/init.lua, lua/mason-core/managers/powershell/init.lua, lua/mason-core/managers/std/init.lua, lua/mason-core/spawn.lua, lua/mason-registry/index/ltex-ls/init.lua, lua/mason-registry/init.lua, lua/mason/api/command.lua, lua/mason/health/init.lua, tests/mason-core/EventEmitter_spec.lua, tests/mason-core/managers/powershell_spec.lua, tests/mason-core/terminator_spec.lua, tests/mason-core/ui_spec.lua, tests/mason/api/command_spec.lua
Explicitly schedule via `a.wait(vim.schedule)` instead.
=> refactor: only schedule in a.scheduler() when in fast event

lua/mason-registry/sources/github.lua, lua/mason-vendor/zzlib/inflate-bit32.lua, lua/mason-vendor/zzlib/inflate-bwo.lua, lua/mason-vendor/zzlib/init.lua
Download data of the registry suggest that ~10-18% struggle to unpack the registry archive, with the drop-off occurring in the `unzip` step. Being able to unpack the registry is a very crucial component of mason.nvim, which warrants vendoring [zzlib](https://github.com/zerkman/zzlib) to allow unpacking it entirely in Lua.
=> feat: vendor zzlib for unzip

lua/mason-core/installer/managers/npm.lua, lua/mason-core/semver.lua, lua/mason-vendor/semver.lua, tests/mason-core/installer/managers/npm_spec.lua
=> fix(npm): set install-strategy on npm >= 9

lua/mason-core/async/init.lua
Still somewhat arbitrary, but high enough to not cause issues such as timing out CI jobs.
=> refactor(async): increase wait time

lua/mason-core/log.lua
Set MASON_VERBOSE_LOGS=1 to print logs (note, these are still always written to :MasonLog).
=> refactor(log): dont print to console when headless by default

lua/mason/health.lua
No longer a hard requirement due to vendoring lua zzlib.
=> chore(health): relax unzip requirement

lua/mason-registry/sources/lua.lua
The index table may get out of date if a user updates the plugin version without restarting Neovim, causing the
`require()` call to error (note, restarting Neovim after plugin updates is always a good idea).
=> feat(registry): pcall require Lua registry packages

lua/mason-core/installer/registry/providers/github.lua, tests/mason-core/installer/registry/providers/github_spec.lua
This makes it so that after parsing the source, the `{{source.asset.file}}` context value points to the downloaded file,
rather than the raw value. This is helpful for source definitions such as:
```yaml
source:
id: pkg:github/mrjosh/helm-ls@v0.0.3
asset:
- target: win_x64
file: helm_ls_windows_amd64:helm_ls_windows_amd64.exe
bin:
helm_ls: "{{source.asset.file}}"
```
=> fix(github): use evaluated out_file as asset file value

lua/mason-core/functional/init.lua, lua/mason-core/functional/relation.lua, lua/mason-core/installer/registry/expr.lua, tests/mason-core/functional/relation_spec.lua, tests/mason-core/installer/registry/expr_spec.lua
The removed filters are not used by mason-registry and are too Lua-specific in nature.
=> refactor(expr): remove redundant core filters and always stringify reduced value

doc/mason.txt, lua/mason-registry/init.lua, lua/mason-registry/sources/github.lua, lua/mason-registry/sources/lua.lua, tests/mason-registry/registry_spec.lua
This is a faster method than .get_all_packages() due to the fact that it only loads package specifications without
instantiating mason-core.package instances. Useful for situations where one only needs to read spec data.
=> feat(registry): add .get_all_package_specs()

lua/mason-core/fs.lua, lua/mason-core/installer/linker.lua, tests/mason-core/installer/linker_spec.lua
Renaming the file will move it from its original installation directory. While reaching into package installation
directories is unsupported and not recommended, it seems to be done pretty broadly. In order to avoid unnecessarily
breaking people's configs we copy the file instead, for now. (tip: use the stable locations inside $MASON/share
$MASON/opt $MASON/bin, if a package is missing a link please open an issue/PR).
This will be reversed back to use uv_fs_rename() in 1.x.x.
=> refactor(linker): copy_file instead of rename on Windows

lua/mason/ui/components/main/package_list.lua, lua/mason/ui/instance.lua
=> feat(ui): display "update all" hint

README.md
This is really not necessary and is problematic because the plugin must have been setup before this command is executed.
=> docs: remove :MasonUpdate from plugin manager lifecycle

README.md, lua/mason-core/installer/managers/std.lua, lua/mason-core/managers/std/init.lua, lua/mason/health.lua, tests/mason-core/installer/managers/std_spec.lua
Addresses #1415.
These changes are needed because the relevant code currently assumes GNU tar features like automatic decompression and the `--no-same-owner` flag, but doesn't detect and use GNU tar on platforms where it's named gtar. This causes a number of failures.
With these changes, the health check passes and tarballs are correctly unpacked on platforms other than Linux. This fix affects at least OpenBSD, and probably other systems like FreeBSD, NetBSD, DragonFly BSD, etc.
tests(std_spec.lua): add a local function named get_tar_cmd() that returns the correct version of tar to call. Adjust the tests so that they call gtar when appropriate.
docs(README.md): update requirements so that they explicitly state that GNU tar is used. Clean up requirements by placing them in separate bullet …
=> fix(std): use gtar if available

lua/mason-registry/sources/init.lua
This should only be called once (during mason.nvim setup), but this fixes potential duplicate registry registration in
cases where it's called > 1 times.
=> fix(registry): reset registries state when setting registries

lua/mason-registry/sources/init.lua
This primarily fixes `file:` registry identifiers on Windows that may include a drive letter (e.g.
`file:C:\Users\user\AppData\Local\nvim`).
=> fix(registry): fix parsing registry identifiers that contain ":"

lua/mason-core/installer/managers/pypi.lua, tests/mason-core/installer/managers/pypi_spec.lua, tests/mason-core/installer/registry/link_spec.lua
=> fix(pypi): support MSYS2 virtual environments on Windows

lua/mason-core/ui/display.lua, tests/mason-core/ui_spec.lua
This PR prevents indentation from being added to blank lines in the UI, which in turn allows the user to move between sections using the `}` keybind. Here's an example gif:
Closes #1529
=> feat(ui): remove whitespace in empty lines

lua/mason-core/installer/managers/pypi.lua, lua/mason-core/managers/pip3/init.lua, lua/mason/health.lua, tests/mason-core/managers/pip3_spec.lua
This is inconsistent with how other system dependencies are resolved and is not
documented anywhere.
=> feat: don't use vim.g.python3_host_prog as a candidate for python

lua/mason-core/functional/type.lua
When this module is lazily required inside functional/init.lua we may be inside a fast event, causing the module to fail
to load due to the top-level call to vim.fn.has.
=> fix: avoid calling vim.fn.has inside fast event

lua/mason-core/installer/managers/pypi.lua, tests/mason-core/installer/managers/pypi_spec.lua
Support for python3.12 among pypi packages is pretty poor, this limits the upper bound to python3.11 instead.
=> fix(pypi): exclude python3.12 from candidate list

lua/mason-core/installer/managers/pypi.lua, tests/mason-core/installer/managers/pypi_spec.lua
Make stock python a go-to choice rather than specific version if stock python is supported version.
When a user activates a virtual environment, one assumes that all python thingies happen on their virtual environment python, not the system python.
Closes #1748.
=> Make stock python a high priority

lua/mason-core/package/init.lua, tests/mason-core/package/package_spec.lua
Hello, this is a simple PR to change the way `vim.validate` is called because of a deprecation in Neovim
This closes https://github.com/williamboman/mason.nvim/issues/1875
=> Fixed deprecated calls of vim.validate

README.md, doc/mason.txt, lua/mason-core/ui/display.lua, lua/mason/settings.lua, lua/mason/ui/colors.lua
`Lazy` plugin manager creates a backdrop right behind its main floating window. This helps to draw our attention to the main window. It would be nice if `mason` could adopt this idea.
As you can see, the backdrop brings depth to the main floating window, thus creates a better UI/UX.
=> feat: add backdrop

lua/mason-core/process.lua, lua/mason-core/spawn.lua, tests/mason-core/spawn_spec.lua
This fixes issues on Windows where uv_spawn fails to locate certain
types of executables in PATH.
=> fix(spawn): expand executable paths on Windows before passing to uv_spawn

lua/mason-core/spawn.lua
=> fix(spawn): fix locating exepath on Windows systems using a Unix `'shell'`

lua/mason/ui/instance.lua
Problem: Custom border characters in winborder was just added. It needs to be a list of characters. `vim.o.winbar` gives the string value with comma separated items which is invalid.
Solution: Just never explicitly set the border if winborder option exists. From the docs of winborder:
> 	Defines the default border style of floating windows. The default value
is empty, which is equivalent to "none".
=> fix(border): only set border to none if winborder doesn't exist

lua/mason-core/installer/compiler/compilers/cargo.lua, lua/mason-core/installer/compiler/compilers/gem.lua, lua/mason-core/installer/compiler/compilers/pypi.lua, lua/mason-core/installer/compiler/init.lua, lua/mason-core/package/init.lua, tests/mason-core/installer/compiler/compiler_spec.lua, tests/mason-core/installer/compiler/compilers/cargo_spec.lua, tests/mason-core/installer/compiler/compilers/gem_spec.lua, tests/mason-core/installer/compiler/compilers/pypi_spec.lua
Previously this field had to be handled separately in each source type
(currently only supported by `cargo`, `gem`, `pypi`). This
backwards-compatible change makes `supported_platforms` a universal
top-level field on the `source:` object, meaning it'll be parsed for
each source type.
PR to modify the schema: https://github.com/mason-org/registry-schema/pull/17.
=> feat(compiler): make `supported_platforms` a universal source field
